import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "google-adsense-account": "ca-pub-8257422205010266",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
          `}
        </Script>
        <script async src="https://pagead.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6769649655859038" crossOrigin="anonymous"></script>
      </head>
      <body className="min-h-full flex flex-col">
        {children}

        <Script
          src="https://pl31175674.profitableratecpmnetwork.com/f4/e0/db/f4e0db51f1d6530d50e6654126e3695e.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}





